version: '3.7'

name: vilki_palki

services:
  postgresql:
    container_name: postgresql
    image: 'postgres:15.3'
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_DB=avada_slj_vp'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: java-app
    build: .
    ports:
      - "80:8080"
    depends_on:
      - postgresql
    volumes:
      - app_images:/files
volumes:
  app_images:
  postgres_data: